### ISSUE TITLE
Add UTC as an available timezone

### ISSUE THREAD

**Issue by apmilen** [abhishekbanthia/Clocker#10]
I would definitely set UTC as my favorite timezone.

**Comment by abhishekbanthia** [comment]
According to this [article](https://www.timeanddate.com/time/gmt-utc-time.html), GMT and UTC both share the same time in practice. 

GMT is available in Clocker. You can search for GMT under the Search for Timezone(s) tab, add it, and rename it to UTC. Hope this helps.

**Comment by apmilen** [comment]
Got it. I thought GMT changes in-timezone for daylight savings but it looks like the UK switches to a new timezone during the summer months (BST). Thanks!
