### ISSUE TITLE
Add UTC timezone

### ISSUE THREAD

**Issue by andru** [abhishekbanthia/Clocker#11]
It seems that it's only possible to add a timezone via a physical location. It'd be great to have the option to define UTC, since that's not subject to daylight savings adjustments and makes for a reliable way to coordinate between a group of people in different timezones.

**Comment by andru** [comment]
Just incase anyone else needs this, I'm getting around it by using Iceland as my favourite, which uses UTC without daylight savings adjustments.

**Comment by dodekeract** [comment]
This is definitely a good idea. I'm surprised this isn't in Clocker already. I'd 100% add that to my list of TZs.

**Comment by abhishekbanthia** [comment]
Andru,

Clocker has a list of timezones you can add. You can browse through the timezones by clicking on _Search by Timezone(s) tab_:

<img width="551" alt="screen shot 2016-10-27 at 11 52 11 am" src="https://cloud.githubusercontent.com/assets/8280282/19780916/ee03394c-9c3b-11e6-887e-95debe43285a.png">

**Comment by abhishekbanthia** [comment]
Also, note UTC is not a timezone, it's a standard on how the time is measured and coordinated, and hence Clocker does not include this. GMT and UTC share the same time in practice; so hope the workaround works out for you. :)

**Comment by andru** [comment]
Though it's not a physical timezone, it is a time system used by many to
co-ordinate activity.

I can't see any way to actually select GMT. Rather, it only seems possible
to select cities/countries which subscribe to GMT as their *base* system
(e.g. the UK) but which may have varying system of summer time which alter
that system for some of the year. The UK, for example, uses BST (UTC/GMT+1)
throughout the summer and GMT in the winter.

I think an ability to select UTC would be really useful.

Anyway, I'll continue using the work-around, although it's not at all an
obvious one for anyone using the app wishing to have UTC as an option,
since just choosing a country on GMT is not enough: one has to choose a
country which is on GMT all year around.

Thanks for the great app either way :)

**Comment by abhishekbanthia** [comment]
Thank you for the reply. Can you elaborate on what do you mean by "I can't see any way to actually select GMT?". (Check out the reference screenshot in the comment above; the timezone Africa/Abidjan corresponds to GMT)

If you head over to the _Search By Timezone(s)_ tab, there is a tableview which lists all the timezone(s) provided by Apple's NSTimezone class. (based on the Olsen DB).

For your particular example i.e. 'UK', there's a timezone _'Europe/London'_ which you can find in the list. My date calculations are done using NSTimezone's timezoneWithName: method, which ['provides the most accurate time-zone, as it adjusts for the daylight saving time.'](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/DatesAndTimes/Articles/dtTimeZones.html) I hope this addresses your varying time differences question.

**Comment by dodekeract** [comment]
@abhishekbanthia his point is that he wants an option that **guarantees** to not be affected by daylight saving time.

**Comment by robinst** [comment]
I can see a GMT time zone in Search by Timezone:

![screen shot 2016-11-22 at 11 46 29](https://cloud.githubusercontent.com/assets/16778/20506604/55528b26-b0a9-11e6-88d6-0487c6870a57.png)

**Comment by abhishekbanthia** [comment]
The separate GMT timezone should take care of this issue.
