### ISSUE TITLE
Support displaying seconds.

### ISSUE THREAD

**Issue by creechy** [abhishekbanthia/Clocker#12]
Would be great if Clock would support displaying seconds, not just minutes.

**Comment by russelltrafford** [comment]
Not to 👎  your feature request, but hmm, optional please. Especially not on the Favorites given the big performance hits that were found in https://github.com/abhishekbanthia/Clocker/issues/8 from frequent updates to the taskbar :P

**Comment by creechy** [comment]
Sure optional is fine. I use a very old program called Meridian right now, not sure if you can even find it anywhere. It does support second resolution. Never noticed any performance problem with menubar updates.

There are times when I am waiting for something to occur at the turn of a minute, its nice to see how long I have to wait :-)

**Comment by abhishekbanthia** [comment]
The new update now supports displaying time with seconds. Here's the iTunes link: https://itunes.apple.com/us/app/clocker-menubar-world-clock/id1056643111?mt=12

Closing.
