### ISSUE TITLE
Option to display date in menu, not just day of the week.

### ISSUE THREAD

**Issue by creechy** [abhishekbanthia/Clocker#13]
Sometimes when dealing with different timezones with days before or behind you, its easier to just see the date (as well as the time) not just the day of the week. 

Would be great if Clocker had another Day Display Option to display the full calendar day (i.e. Fri Nov 18, 2016). 

Also, noticed that there's no option at all to display the year.

**Comment by abhishekbanthia** [comment]
Thanks for the feedback. This, along with your other issue, is something I've been planning to incorporate since a long time (so yeah keep an eye out for the next version).

**Comment by abhishekbanthia** [comment]
Hi @creechy, just want to clarify you'll like to see the date in the Panel right?

<img width="340" alt="screen shot 2017-01-17 at 4 03 19 pm" src="https://cloud.githubusercontent.com/assets/8280282/22039044/a61cafde-dccb-11e6-992e-2a29504710cd.png">

**Comment by creechy** [comment]
Hi.

I mainly wanted seconds in the Menubar. I saw your release and installed it. Just what I was looking for. Thanks!

  --joe

**Comment by abhishekbanthia** [comment]
Great. Closing.

**Comment by creechy** [comment]
The only slight nit-pick is that the font used for the Menubar doesn't appear to be 100% monospace (under macOS Sierra) and so the Menubar items bounce around slightly as seconds tick by.

**Comment by dodekeract** [comment]
@creechy Can't you just add a 4-8 pixel padding or something around it that balances this?

**Comment by creechy** [comment]
How would you add padding around the item? Are you talking programmatically in Clocker? As long as the padding will let it dynamically expand and decrease without causing the other menubar items to shift over I think this would work.

**Comment by abhishekbanthia** [comment]
@creechy, thanks for raising the monospace issue. Good news is that AppKit actually has introduced support for monospaced fonts through the _NSFont_ class. The next version will feature the menubar text monospaced.

Here's a small demo:

https://streamable.com/3rely

**Comment by creechy** [comment]
Sweet! Look forward to the next release. Thank you.
