### ISSUE TITLE
Use the same font-size as native time

### ISSUE THREAD

**Issue by abdonrd** [abhishekbanthia/Clocker#14]
The Clocker has a little font-size:

<img width="498" alt="screen shot 2017-01-10 at 10 26 09" src="https://cloud.githubusercontent.com/assets/1007051/21800758/50d48d14-d71f-11e6-83c9-fb6f82e761bf.png">

**Comment by abdonrd** [comment]
With the last update:

<img width="414" alt="screen shot 2017-01-17 at 11 20 12" src="https://cloud.githubusercontent.com/assets/1007051/22016537/f0b8a6da-dca6-11e6-8349-3296f0d7c7d5.png">

**Comment by abhishekbanthia** [comment]
Ah, thanks for pointing out. I'll look into this.

**Comment by abdonrd** [comment]
Thanks @abhishekbanthia!

**Comment by abhishekbanthia** [comment]
Redesigning and would love your inputs:

<img width="321" alt="screen shot 2017-01-20 at 12 41 46 pm" src="https://cloud.githubusercontent.com/assets/8280282/22158605/05cc3512-df0b-11e6-95b0-33611bf93d59.png">

**Comment by abdonrd** [comment]
Thanks! I will try when you release it! :)

**Comment by abdonrd** [comment]
@abhishekbanthia When the new release? 🙂

**Comment by abhishekbanthia** [comment]
Hi @abdonrd; I'm busy juggling school, preparing for interviews etc. I've made decent updates for the next version, but there are some issues especially related to multiple monitors that I want to fix. I can't give you a timeline right now, but if you'd like I can upload a unsigned version that fixes #14.

**Comment by abdonrd** [comment]
@abhishekbanthia ok, I will wait until you're free to release it. :)

**Comment by abhishekbanthia** [comment]
Hi @abdonrd, the new update is out. Let me know if you've any feedback. Closing this issue.

**Comment by abdonrd** [comment]
It's nice! Thanks! :)
