### ISSUE TITLE
Booting does not work with OSx

### ISSUE THREAD

**Issue by EdZava** [abhishekbanthia/Clocker#16]
Even with the configuration option marked to boot with the OS the program does not open. 
Always open manually.

macOS Sierra 10.12.1

**Comment by abhishekbanthia** [comment]
Ahh, thanks for pointing that out. Here’s a workaround for adding Clocker to Login Items such that it starts each time you log in:

Here’s how you do it: Go to System Preferences —> Users and Groups —> Current User. Click on Login Items tab and add Clocker by clicking on + icon.

<img width="780" alt="screen shot 2016-08-09 at 10 07 41 am" src="https://cloud.githubusercontent.com/assets/8280282/22374342/d427df2a-e473-11e6-92af-d6c551175da4.png">

**Comment by EdZava** [comment]
thanks 👍

**Comment by abhishekbanthia** [comment]
@EdZava v1.4.1 update is available now on the App Store. You'll have to uncheck and check the "Start Clocker at Login" box again. Closing.
