### ISSUE TITLE
Time is stuck in the future after moving the slider and closing dropdown

### ISSUE THREAD

**Issue by unthingable** [abhishekbanthia/Clocker#17]
^ that

After moving the time slider and closing the window, the last known relative time becomes the "current" time. The slider resets to the left, but the time offset doesn't.

(Clocker 1.4, macOS 10.12.3)

**Comment by abhishekbanthia** [comment]
Thanks for reporting. Issue is reproducible as well. Fix incoming..

**Comment by abhishekbanthia** [comment]
@unthingable v1.4.1 is out on the App Store which should fix your issue. Closing.
