### ISSUE TITLE
Start Clocker at Login not working

### ISSUE THREAD

**Issue by jimvanderveen** [abhishekbanthia/Clocker#18]
I have Clocker 1.4.1 installed (recently updated) on OS X El Capitan (version 10.11.6)
"Start Clocker at Login" is checked, but I have to start it manually whenever I log in.
I don't recall if it worked before updating to 1.4.1

Not urgent, just wanted to file the bug since I don't see one here.

**Comment by abhishekbanthia** [comment]
Hi @jimvanderveen, can you try unchecking and checking the _**"Start Clocker at Login"**_ checkbox? I've actually changed the startup mechanism in the latest version. If it still doesn't work, let me know.

**Comment by jimvanderveen** [comment]
Unchecked, logged out, logged back in. Started Clocker manually, checked "Start Clocker", logged out and back in. Clocker did not start. Sorry. Any other suggestions I can try? Remove/reinstall perhaps?

**Comment by abhishekbanthia** [comment]
Ahh, thank you for the reply. Here’s a workaround: Go to System Preferences —> Users and Groups —> Current User. Click on Login Items tab and add Clocker by clicking on + icon.

<img width="780" alt="screen shot 2017-03-08 at 4 36 16 pm" src="https://cloud.githubusercontent.com/assets/8280282/23725077/299c9d60-041d-11e7-8033-0d56a6f786dc.png">

**Comment by jimvanderveen** [comment]
That worked. Thanks!
