### ISSUE TITLE
Unnecessary scroll bar + lack of some padding

### ISSUE THREAD

**Issue by guiporto** [abhishekbanthia/Clocker#20]
After the latest update, there's a scrollbar on my clocker that I don't recall having it before. Also, I believe you could add some padding on the x axis to make a little white space in it.

<img width="330" alt="screenshot 2017-05-02 17 50 20" src="https://cloud.githubusercontent.com/assets/1811399/25638768/ddde3c3a-2f5f-11e7-98d0-53e4076bf414.png">

**Comment by abhishekbanthia** [comment]
Woah; that looks ugly. Can you tell me the following things:

1. Which OS are you using?
2. Are you using multiple monitors?
3. Did you add just 3 timezones?

**Comment by guiporto** [comment]
1. I’m using Mac OS Sierra 10.12.4 (16E195)

2. Yes I’m using multiple monitors, but the issue also happens when I disconnect them (just tried it)

3. Yes, only those 3 timezones

On Tue, 02 May 2017 at 17:59 Abhishek Banthia

<
mailto:Abhishek Banthia <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Woah; that looks ugly. Can you tell me the following things:

Which OS are you using?

Are you using multiple monitors?

Did you add just 3 timezones?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/abhishekbanthia/Clocker/issues/20#issuecomment-298759440
, or

**Comment by abhishekbanthia** [comment]
Great; thanks. I'm able to reproduce this while I hover near the right side of the Panel. 

Looking into this.

**Comment by tristinDLC** [comment]
Just reporting in with the same issue. I _just_ updated to 1.5 and have the same unnecessary scrollbar as well as the incorrect padding. Prior to the update I was just having the padding issue and a hunt for a fix is what lead me to update today. I'm running macOS 10.12.4 and app version 1.5 on a MacBook Air which has the problem showing up on both the native screen as well as an external monitor plugged in. Attached is a screenshot of what I am seeing:

![screen shot 2017-06-03 at 4 15 03 pm](https://cloud.githubusercontent.com/assets/24608720/26757675/d111da7a-4878-11e7-9529-f8b9d5cfc8fd.png)

![screen shot 2017-06-03 at 4 21 46 pm](https://cloud.githubusercontent.com/assets/24608720/26757676/d11210da-4878-11e7-9840-af7c4a22f431.png)

![screen shot 2017-06-03 at 4 21 58 pm](https://cloud.githubusercontent.com/assets/24608720/26757674/d10f828e-4878-11e7-86a3-baae608d5191.png)

Other than that, cheers for a great app! I was actually in the process of building something similar based off of BitBar, but your standalone has a better interface for settings. Nice work.

**Comment by abhishekbanthia** [comment]
Hi @tristinDLC,

Thanks for the kind words. I've attached a newer version which fixes the scrollbar issues. Try it and let me know!

[Clocker.app.zip](https://github.com/abhishekbanthia/Clocker/files/1050054/Clocker.app.zip)

**Comment by tristinDLC** [comment]
I did a complete uninstall of the old application and reinstalled with the linked above version. Works like an absolute charm. Nice to see some take some quick action in bug reports. 

Would you be willing to accept a message about a suggestion on some UI/UX with the app? I would love to shoot you an email or something :)

**Comment by abhishekbanthia** [comment]
Absolutely; you can mail me at abhishekbanthia @ me dot com.

**Comment by abhishekbanthia** [comment]
Referenced #23
