### ISSUE TITLE
List of timezones becomes unsorted on drag/drop of a timezone

### ISSUE THREAD

**Issue by peterdalydickson** [abhishekbanthia/Clocker#21]
Steps to create the issue:

1. Have a list of timezones in alphabetical order
2. Add a timezone
3. Drag the new timezone to the correct place in the list

Expected behaviour:

* List stays in alphabetical order, with the newly inserted timezone in the correct place

What actually happens:

* The timezone that was underneath the new timezone before it was dropped in place moves to the bottom of the list

Here's a quick Loom video to highlight the issue - https://www.useloom.com/share/a2f8406c5bcb4c7cbe0d01cf89e10c91

**Comment by abhishekbanthia** [comment]
Ah, okay. Thanks for pointing this out; I'll take a look at this...

**Comment by peterdalydickson** [comment]
Maybe being able to choose 'sort alphabetically', 'by timezone (diff. from GMT)' would be useful too!

**Comment by abhishekbanthia** [comment]
That's an interesting suggestion.

**Comment by abhishekbanthia** [comment]
So I just added sorting(ascending/descending) functionality as well as fixed the drag & drop. I'm attaching the newer version. Do give it a try if you get time.

![out](https://cloud.githubusercontent.com/assets/8280282/25868675/8eebb410-34cb-11e7-8e60-4e3000f1c8d3.gif)

**Comment by abhishekbanthia** [comment]
Here's the newer version:

[Clocker.app.zip](https://github.com/abhishekbanthia/Clocker/files/987790/Clocker.app.zip)

**Comment by peterdalydickson** [comment]
Hmmm... I lost all my timezones :(

**Comment by abhishekbanthia** [comment]
My bad. Should have warned you. Your old timezones should be available from the Clocker version you downloaded from the App Store (should be in the Applications folder).

**Comment by peterdalydickson** [comment]
No probs... it was easy enough to add them back in.

Will my version get updated, or should I install from the App Store again?

Also... my idea about the timezone sort was for it to be different from the
label sort... that it would be in sorted in no. hrs difference from GMT/UTC
- or maybe even from the Favourite... that might make more sense.

e.g. say your cities, in alphabetical order, were Buenos Aires, Coventry,
Houston, Los Angeles, Sydney and Toronto - with Coventry marked as
'Favourite'.

In timezone order, the list would be Los Angeles (-8), Houston (-6),
Toronto (-5), Buenos Aires (-4), Coventry (0), Sydney (+9).

Does that make any sense?! ;)

Great app btw. Found you via lifehacker article.

cheers

P.

—

*Peter Daly-Dickson*
Conquer The Chaos Ltd
Infusionsoft Certified Partner


​

**Comment by abhishekbanthia** [comment]
It makes sense yes :) Timezone sorting has been in my plans but it's kinda tricky to implement & test with the current codebase. But yeah do keep an eye out for the future versions.

Also, you'll need to update the app from the App Store when the new version releases.

Thanks for your feedback.

**Comment by abhishekbanthia** [comment]
Hi @peterdalydickson, Clocker v1.5 has an option to sort the time zones based on time difference in both ascending  and descending order. Go to Preferences and click on the toggle sorting options button. Try it out and lmk.

<img width="697" alt="screen shot 2017-07-16 at 11 36 45 am" src="https://user-images.githubusercontent.com/8280282/28249424-188e4276-6a1b-11e7-922e-5e4b64871364.png">
