### ISSUE TITLE
Multiple display issues

### ISSUE THREAD

**Issue by peterdalydickson** [abhishekbanthia/Clocker#22]
This is the display of all my timezones on my external monitor...

![item-0_and_fantastical_and_item-0_and_item-0](https://cloud.githubusercontent.com/assets/17453188/26106019/69129094-3a3c-11e7-91c3-3057e3a74231.png)

And this is the same list on my laptop...

<img width="403" alt="item-0_and_fantastical_and_item-0_and_item-0" src="https://cloud.githubusercontent.com/assets/17453188/26106040/76572b0c-3a3c-11e7-8b56-699f692a515d.png">

I am unable to scroll the laptop display to reach the time slider and preference icon.

cheers

Pete

**Comment by abhishekbanthia** [comment]
Thanks for reporting this. Looking into it.

**Comment by peterdalydickson** [comment]
Thanks.

Let me know what you find. It's getting annoying! ;)

**Comment by abhishekbanthia** [comment]
Hi @peterdalydickson, are you mirroring your display?

**Comment by peterdalydickson** [comment]
No. It's an external monitor.

—

*Peter Daly-Dickson*
Conquer The Chaos Ltd
Infusionsoft Certified Partner


​

**Comment by abhishekbanthia** [comment]
Does restarting the app help?

**Comment by peterdalydickson** [comment]
On my laptop... yes.

On the external monitor... no.

**Comment by EParrish** [comment]
I am also having a similar issue. Except mine does not show up on the external monitor at all.

**Comment by abhishekbanthia** [comment]
Weird. Are you mirroring display?

**Comment by EParrish** [comment]
No, I have it as an external monitor. Restarting the app did nothing.

**Comment by abhishekbanthia** [comment]
Alright. Can you tell me the following to help me debug the issue:
1. macOS version
2. Clocker version
3. Any custom display setting that you might have turned on/off.

**Comment by EParrish** [comment]
1. macOs Sierra Version 10.12.6
2. Clocker 1.5.1
3. I don't believe I have any extra settings turned on/off. I just plugged it in and rearranged the position of the screen.

Thank you for your help. Clocker is great, it makes scheduling across timezones a lot easier.

**Comment by abhishekbanthia** [comment]
I tried different setups with my two external monitors and my Macbook but I'm unable to reproduce this. :(

**Comment by AfzalivE** [comment]
Also notice how the text is blurred on the external monitor, I'm seeing the same issue

**Comment by abhishekbanthia** [comment]
I was unable to reproduce this last time, but I've two new monitors to play with this time around. I'll take a look.

**Comment by abhishekbanthia** [comment]
Is this fixed @peterdalydickson?
