### ISSUE TITLE
Hotkey doesn't work until you go into preferences

### ISSUE THREAD

**Issue by peterdalydickson** [abhishekbanthia/Clocker#27]
I have ⌘F12 set as the hotkey to open Clocker.

However, after starting Clocker, ⌘F12 only works after I click the cog to open preferences.

**Comment by abhishekbanthia** [comment]
Looking into it.

**Comment by abhishekbanthia** [comment]
That's easily reproducible. The issue is with the shortcut observer not starting when you restart Clocker.

**Comment by abhishekbanthia** [comment]
Hi @peterdalydickson, the new version is out now which should fix this issue. Closing..
