### ISSUE TITLE
up next display

### ISSUE THREAD

**Issue by hezhizhen** [abhishekbanthia/Clocker#28]
I closed the up next part and now I want to enable it, but I have no idea about it.

**Comment by abhishekbanthia** [comment]
Hi @hezhizhen, you'll have to open terminal and execute the following command.

`defaults write com.abhishek.Clocker ShowUpcomingEventView "YES"`

This was a beta feature that I wanted to A/B test. You'll have an option in the preferences section to enable this in the next version.
