### ISSUE TITLE
Ability to change the increment of the future slider

### ISSUE THREAD

**Issue by peterhartman** [abhishekbanthia/Clocker#29]
Most of the time I am not interested in incrementing the slider by 1 minute at a time, it would be good to have the option for the slider to increment in larger chunks at a time, eg. 5, 10, 15 mins.

**Comment by abhishekbanthia** [comment]
I'm working on this for the next version. One feedback that I received was that the slider could let you see only one day in the future. So, I'm increasing this range and making this user customizable:

<img width="549" alt="screen shot 2017-09-19 at 9 57 59 am" src="https://user-images.githubusercontent.com/8280282/30599167-4275218e-9d21-11e7-8bdd-aae2fbebf53f.png">

Would something like this help you?

**Comment by unthingable** [comment]
Quantizing the time ruler by the hour would be the most useful for me personally (until I work with India, the minutes are the same everywhere and I can mentally extrapolate 20:00 to 20:45 quite easily).

**Comment by abhishekbanthia** [comment]
That makes sense. I'm leaning towards providing slider time options which Peter suggested; 15 mins, 30 mins, hour, day etc. By default, I'm planning to set this as an hour.

**Comment by peterhartman** [comment]
1 hr default sounds great to me.
 
@unthingable, watch out! Not just India that has :30 or :45 offsets:
https://www.timeanddate.com/time/time-zones-interesting.html

**Comment by abhishekbanthia** [comment]
New version with this setting's out on the App Store. Closing.
