### ISSUE TITLE
height problems

### ISSUE THREAD

**Issue by unthingable** [abhishekbanthia/Clocker#30]
Thanks for the slider increments!

Timezone panel height calculations looks off (and it's not possible to scroll to see all of "GMT"):

<img width="346" alt="clocker" src="https://user-images.githubusercontent.com/925755/33733169-3178e36a-db89-11e7-9652-2d89ee3e818a.png">

**Comment by abhishekbanthia** [comment]
Been fixed in the upcoming version. I've released an update for the App Store (pending Apple's approval).

**Comment by unthingable** [comment]
😍
