### ISSUE TITLE
Slider increments, steps and range

### ISSUE THREAD

**Issue by unthingable** [abhishekbanthia/Clocker#31]
Changing the value of an increment doesn't change the slider step size or range, so 1 hour increment covers three months of time in pixel-sized steps.

It would be far more useful for the range to remain unchanged (at least for sub-day increments) and for step size to increase proportionally to the increment.

**Comment by peterhartman** [comment]
+1 for @unthingable's point above. I would be happy for the slider range to be fixed at 1-1.5 day (either side if you are including issue #6)

**Comment by RomeshA** [comment]
I would +1 this too, usually I would be wanting to schedule things in next 24-48 hours, so currently it is quite difficult to select a specific time because the tiniest movement corresponds to a huge change in time

**Comment by amit0rana** [comment]
+1

**Comment by AbdealiJK** [comment]
+1 from me too - sliding is a bit tough right now.

**Comment by slackmage** [comment]
You can build it from the source and adjust the sensitivity of the slider by dividing by some number. I chose 50.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/230274/42357447-f86a4844-80a5-11e8-871c-ee2e2acb78f6.png">

**Comment by abhishekbanthia** [comment]
A date picker in the Future has been added to Future Slider enhancements! If this doesn't solve the issue, re-open the issue and let me know your use-case!

**Comment by unthingable** [comment]
Reopened as #46 .
