### ISSUE TITLE
Allow 12/24 hour choice by timezone

### ISSUE THREAD

**Issue by leegenes** [abhishekbanthia/Clocker#32]
I'm using a local US timezone, and UTC. Would be really great if it were possible to use 12 hour for local time, and 24 hour for UTC.
Possible enhancement as in the US most interact with 12 hour day-to-day, but UTC is convenient to see 24 hr at a glance.

**Comment by abhishekbanthia** [comment]
Working on it for the next version.

**Comment by britcey** [comment]
I'd love this too, with a variant - I'd like my local time to be AM/PM in the taskbar, with 24-hour time for timezones shown in the dropdown.

**Comment by abhishekbanthia** [comment]
Available in 1.6.02!
