### ISSUE TITLE
Status bar time not updating

### ISSUE THREAD

**Issue by abhishekbanthia** [abhishekbanthia/Clocker#33]
"With the new update the time when viewed in the status bar seems to not be updating any more. I need to go into config, add a ‘favourite’ then remove it again and this will update the time"

**Comment by chere005** [comment]
Time doesn't update properly after new update.. Though I also just updated to High Sierra, but I'm pretty sure it's the clocker update. It'll update after I click my status bar.

**Comment by abhishekbanthia** [comment]
Have you, by any, chance, turned on the option of "Showing Next Meeting Title in the menubar"?

**Comment by chere005** [comment]
Hmm, I'm unable to reproduce now. I don't see that option, possibly because
I haven't granted cal access

**Comment by abhishekbanthia** [comment]
Aha. That's the challenge, I'm having a hard time reproducing it as well.

**Comment by chere005** [comment]
I shall try to pay attention.. Is there any info I can try to get if it
happens again?

**Comment by abhishekbanthia** [comment]
If you can, send me a screenshot of your Clocker settings (Command + ,) and then click on the Appearance tab when it happens. Also, keep an eye out for the following:
1. Did it occur after a restart/awake after sleeping?
2. Does it occur at a particular time in the day? Or when you add a particular timezone? Basically, as much information about the circumstances.

Thank you for your help :)
