### ISSUE TITLE
Timezone duplicated in menu bar

### ISSUE THREAD

**Issue by leegenes** [abhishekbanthia/Clocker#34]
Potential bug

Seeing this:
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_169180/1JUgdLeS3SEyeesSdmeLGoMzoc2iyN/Item-0%2B2017-12-13%2B16-46-59.png?Expires=1513299016&Signature=QG8g2Th0Geg3aPyx-Q~XtMR4DdWcsAxoEl3WJegsBFN~1KE8emCnMg-ZNttkDzUUHK8NshoiMwtZ4MM7JzhJn6DhjgaE8FeFo87Hm5HAtkD9eDLVYlzLsd3kTw2FYHpsWvx-7ux8jAPbBHhnAL1g7RHrQa75wnE8LnJ83Eqkwdk6U~l828eFH8K8kDAlFiTaMJ~Kjr51GqIkI1pPTgXRprJrFNYc2-NuoMUqBIQu486jfM2ynLBVh6TfbSph~QxyVHpL1nszvxiO0t6h5QoffmyIP1T8Y-RQ64NtQMbaNAiY1kedHdD6o5Py52MxLxPPSZeMbrPloHshF899p0aBhA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

While settings are this:
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_169180/9oRsXsKGB8PiBe9T508YGTxtXkD9h8/Clocker%2B2017-12-13%2B16-48-39.png?Expires=1513299046&Signature=N22WrSCOHwCXIo6NAAb7wqA6q0bzjEmPmdXtSU-0ICfgsGmZeDzIViYGWP8SVUR1PFed2AFRg373oeARELkgLSA5Z3FQPMmU7FvVgh6oyjfhGRYCTVUd5d~Y9Y3OZIftnKexMX86m1SVGos5tX0JWKRC4uAEEzUuFdkTg8VXsvzOekE30xcIrZTd-f5KElWonCaWX2zT5iKReB-rafiC0dhuy4q5Uf2RkOosAowqTmjuYD2M4otcPjevYITdaKQDSJtTpX0FWr8t7UiGY1syVhWuYLIYE4LqUDDckMdVFuLvRBAGcrIFnCpKtsilHleRv0Fho9~lQvlqA7FGZd1eDg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Until I open a settings dialog. Then, I see this:
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_169180/PZ41NDhktxtdEZz4rTFwWONzXrUlpW/Item-0%2B2017-12-13%2B16-49-48.png?Expires=1513299059&Signature=QBTpQpo~YFi2~EbZPfYYAaMGh9mLpcCuZX-HbXYFnP1pgbMGSvpGH5LaWqZkqk50TYvA5xGLspG6hQ5ACCAMROZhIpb-j7xBLIZtLFatjILAyVSBlL0X~BQPhrRTEZyy4m-olfTkkFGvjxCXjHZ~Utndryw~8ryb~3bQg-ckqYvrWRNTR6eK323FHxccMDy0mxVY9Xm7sTLdxnB29IVaX4xcfV4TW7RXRuyfA7eXk4cptf2VGdA74bBcj7dHSrC074-pcOmlufXPNt1OHOUcDXEhx67Lox7xD818iNU6oJ3PK-TV6ctRkse71eJHLYYfLp-zOBRvlQQs6sMR7glEoA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by abhishekbanthia** [comment]
Hi @leegenes, can you reattach the images? This is what I'm seeing:

<img width="785" alt="screen shot 2017-12-14 at 10 39 49 pm" src="https://user-images.githubusercontent.com/8280282/34027044-c1dc5c16-e11f-11e7-896a-395a9773badd.png">

**Comment by leegenes** [comment]
oh! not ideal. sorry about that.
![tz](https://user-images.githubusercontent.com/13713190/34061485-6a194c40-e19d-11e7-9601-bd63c756de7f.png)

**Comment by abhishekbanthia** [comment]
Yikes. Thanks for the images. I'll take a look.

**Comment by grishka** [comment]
I've just had this exact thing happen. I'm using a dual-display setup (a MacBook with a monitor) if that matters. I fixed it by unchecking the single timezone I've added and then checking it again and it no longer reproduces even if I restart the app.

**Comment by abhishekbanthia** [comment]
This should be fixed in one of the previous releases.
