### ISSUE TITLE
Sliding the bar at the bottom is crashing the app

### ISSUE THREAD

**Issue by vamsivinay** [abhishekbanthia/Clocker#37]
This behavior is observed after the new update 1.5.23.
If you click at specific spot then that's fine but if you slide then its getting crashed. 

Its also getting crashed when I slided it back after clicking to a specific time stamp.

![image](https://user-images.githubusercontent.com/19917082/37114284-df5533bc-2215-11e8-8426-6508e91a8e34.png)

**Comment by abhishekbanthia** [comment]
Thanks for reporting this. This is scarily easy to reproduce. Investigating.

**Comment by abhishekbanthia** [comment]
A new update is out on the App Store which fixes this issue. Closing this. Feel free to reopen if you encounter this again.
