### ISSUE TITLE
Allow changing time manually

### ISSUE THREAD

**Issue by AbdealiJK** [abhishekbanthia/Clocker#39]
The slider is great to see the time in the future, but I would love to be able to simply double-click on my NewYork timezone and say "23:30" and see what times the other timezones will be at.

This makes it simpler to just search for a specific time and see what that time in other zones is.

**Comment by abhishekbanthia** [comment]
Available in 1.6.02!

**Comment by eduardo-haro** [comment]
Hi,
I see the fix is in 1.6.02 version however I have the app via App Store and I'm using version 23.01 (109), so I'm not sure how could I request this update to 1.6.02 version.
do you know if this fix will be updated in the App Store for Mac version also?
