### ISSUE TITLE
Taking >20% CPU

### ISSUE THREAD

**Issue by SashaOv** [abhishekbanthia/Clocker#4]
Great program, thanks for making it! I noticed that it is taking >20% CPU on my Mac. Is there a reason for that and how can I fix it?

Here is the screenshot: http://imgur.com/oreGUSu

Thanks.

**Comment by Abhishaker17** [comment]
One of the reasons for increased CPU usage can be if you have set a favorite city for your menu-bar (there's a timer which constantly updates), but this is abnormal.

Can you share with me the following things:

   1. OS X version (for e.g. : 10.10, 10.11)
   2. OS X device you're using (for e.g. : Macbook Pro, iMac etc)

**Comment by ry29** [comment]
I have the same issue.
OSX 10.11.5 on a 2015 Macbook Pro

**Comment by prokher** [comment]
More to this:
![2016-09-10_17-56-45](https://cloud.githubusercontent.com/assets/399393/18411448/c350dae2-7788-11e6-803d-b7f4d09717b8.png)

**Comment by abhishekbanthia** [comment]
Would you be willing to install a new unsigned version of the app which attempts to fix these issues?

**Comment by prokher** [comment]
I could try

**Comment by abhishekbanthia** [comment]
Attached an unsigned copy which uses a different mechanism to update the menubar. Let me know how does this work for you:

[Clocker.zip](https://github.com/abhishekbanthia/Clocker/files/478960/Clocker.zip)


_(This has been tested only on my machine. So bear with me if it still does not fix the energy consumption issue)_

**Comment by prokher** [comment]
On the first start it shown me some intro but then crashed. Trying to run
it after that does nothing at all:

> ./Clocker
2016-09-26 14:05:50.847 Clocker[39469:506582] iRate verbose logging enabled.
2016-09-26 14:05:50.879 Clocker[39469:506582] *** -[NSCalendar
component:fromDate:]: date cannot be nil

and hanging...


On Sun, Sep 18, 2016 at 11:08 PM, Abhishek Banthia <notifications@github.com

**Comment by dodekeract** [comment]
Related to #4.
@SashaOv @ry29 @prokher Are you using multiple displays? Everyone we've asked so far has multiple screens.

**Comment by abhishekbanthia** [comment]
#8

**Comment by abhishekbanthia** [comment]
The new update should fix the issue.

Here's the update link: https://itunes.apple.com/us/app/clocker-menubar-world-clock/id1056643111?mt=12

Closing.
