### ISSUE TITLE
Upgrading to v1.5.25 causes system hang/crash

### ISSUE THREAD

**Issue by laghee** [abhishekbanthia/Clocker#40]
Version 1.5.1 (installed with homebrew) was working fine, but when I followed prompts to upgrade to 1.5.25 and tried to re-open the app ... everything blew up. While Clocker didn't look like it was open, it showed up in Activity Monitor. But the fan kicked into overdrive almost immediately, all the icons in the menu bar (Dropbox, Google Drive Sync, system indicators) disappeared, and response went sluggish.

On a MacBook Air running OS 10.13.4, High Sierra

**Comment by abhishekbanthia** [comment]
Hi @laghee, have you selected multiple favorites?

**Comment by laghee** [comment]
Yep, 7.

**Comment by abhishekbanthia** [comment]
Aha. If there isn't enough space on the menubar for all 7 places, macOS hides Clocker (making it look like the app isn't open). I suggest reducing the number of favorites as I work on a more compact menubar design. Thanks.
