### ISSUE TITLE
Source code for v1.6?

### ISSUE THREAD

**Issue by l2dy** [abhishekbanthia/Clocker#42]
Hi, I noticed that this repository hasn't been updated for a year, but the app on the Mac App Store has been updated recently. Will you publish its source code?

**Comment by abhishekbanthia** [comment]
Yes. There are definite plans. I just converted the whole app to use Swift. I still need to do some cleanup and refactoring. As soon as that's done, I'll push everything here.

**Comment by rhuanbarreto** [comment]
You can simply open a branch, delete all the contents and put the code there. Then we can have a look and make some fixes.

**Comment by n0shake** [comment]
Repo has been updated!
