### ISSUE TITLE
24-hour option incorrectly shows "AM" or "PM"

### ISSUE THREAD

**Issue by Drarok** [abhishekbanthia/Clocker#49]
A 24h clock is designed to make morning/afternoon unambiguous, so "AM" or "PM" can (and _should_) be omitted.
![screen shot 2018-09-11 at 00 40 05](https://user-images.githubusercontent.com/55830/45330067-7981c800-b55b-11e8-8f80-2194b59d1337.png)

**Comment by abhishekbanthia** [comment]
Fix incoming!

**Comment by abhishekbanthia** [comment]
[Fixed in 1.6.05](https://itunes.apple.com/us/app/clocker-menubar-world-clock/id1056643111?mt=12). Reopen the issue if this is not fixed; thanks.
