### ISSUE TITLE
Multi Monitor 

### ISSUE THREAD

**Issue by brycampbell** [abhishekbanthia/Clocker#50]
New version now has broken multi monitor support. Only appears on the 'main desktop'.

MacOS 10.12.6 (16G1510)

**Comment by abhishekbanthia** [comment]
Can you send me a screenshot if possible? I use 2 monitors + my Macbook and I haven't seen any issues.

**Comment by brycampbell** [comment]
Did you try on MacOS 10.12.6 (16G1510)

?

**Comment by abhishekbanthia** [comment]
I haven't. I have two machines which are on 10.13 and 10.14. Can you tell me the following:

1. Which Clocker version are you on?
2. Are you mirroring your displays?

**Comment by brycampbell** [comment]
No not mirroring the displays. Version 1.6.05 (57)
