### ISSUE TITLE
Clocker steals focus from active window

### ISSUE THREAD

**Issue by ryandesign** [abhishekbanthia/Clocker#51]
When I click the Clocker menu bar widget, it removes the focus of the active window. This is inconvenient when I am typing into a window but need to get information from Clocker to complete what I was typing, because then I have to remember to click back into my window to refocus it before continuing to type. I haven't encountered any other menu bar items that steal focus.

**Comment by abhishekbanthia** [comment]
Clocker's menu bar widget resides in an [NSWindow](https://developer.apple.com/documentation/appkit/nswindow). When you click on the menubar item, Clocker's window becomes the key window thereby causing the previously active window to lose focus. As far as I've seen, other popover based menubar apps display the same behaviour.
