### ISSUE TITLE
Settings are not working in macOS Mojave

### ISSUE THREAD

**Issue by warapitiya** [abhishekbanthia/Clocker#53]
Some of the settings are not working/apply in macOS Mojave. 

- Dark theme

<img width="396" alt="screen shot 2018-09-25 at 7 37 50 pm" src="https://user-images.githubusercontent.com/6380518/46012091-9d681080-c0fa-11e8-9f54-22d2eee83794.png">
<img width="707" alt="screen shot 2018-09-25 at 7 38 07 pm" src="https://user-images.githubusercontent.com/6380518/46012097-a0fb9780-c0fa-11e8-9b96-866065a20895.png">

**Comment by abhishekbanthia** [comment]
Apple just approved version 1.6.06. If you're on Mojave, it'll follow your system appearance for light/dark theme! Reopen this if you see any issues.
