### ISSUE TITLE
How can I activate 1.6.07 compact mode?

### ISSUE THREAD

**Issue by rraallvv** [abhishekbanthia/Clocker#55]
No sure if this is an issue, but I upgraded to version 1.6.07 and can't find where the option to enable compact mode is in the settings. Is it enabled by default? Could you please share a screenshot showing how it's supposed to look compared to the non compact version? Thanks.

Keep up the good work.

**Comment by abhishekbanthia** [comment]
You can find the option under Menubar Display Options. You'll need to favourite at least one timezone before you can access Menubar Display Options. Here's a screenshot:

<img width="707" alt="menubar modes" src="https://user-images.githubusercontent.com/8280282/50026372-54fc1880-ffae-11e8-9d64-a87bd7226a63.png">

**Comment by abhishekbanthia** [comment]
This is how it looks with the standard mode:

<img width="512" alt="screen shot 2018-12-14 at 2 41 46 pm" src="https://user-images.githubusercontent.com/8280282/50026414-7eb53f80-ffae-11e8-9ba3-79d1bc07c8e2.png">

**Comment by abhishekbanthia** [comment]
And this is how it looks with the compact mode:

<img width="281" alt="screen shot 2018-12-14 at 2 38 45 pm" src="https://user-images.githubusercontent.com/8280282/50026428-8aa10180-ffae-11e8-9332-6e64b986b4f4.png">

**Comment by rraallvv** [comment]
Thanks, I just saw I need to favorite a timezone to enable the menubar display options. I totally misunderstood what it does, I thought enabling compact mode would make the pop-up menu occupy less real estate on the screen. Thanks for the clarification.
