### ISSUE TITLE
Past time slider

### ISSUE THREAD

**Issue by indigoviolet** [abhishekbanthia/Clocker#6]
It's often useful in development work to be able to look at past time events in some time zone and convert quickly to another timezone.

**Comment by abhishekbanthia** [comment]
That's an interesting feature request. I'm thinking about the UI challenges (especially with the current slider), but yeah, thank you for your input.

**Comment by peterhartman** [comment]
![7588e714-6c9f-11e4-85f1-a89a6c1cff0b](https://user-images.githubusercontent.com/1226762/34037910-61aca2de-e182-11e7-9500-09d216b27925.png)

A time slider that starts in the middle and lets you go back or forward in time (with some indication which way you have moved -ive or +ive)

**Comment by abhishekbanthia** [comment]
1. I've had rarely had feedback suggesting users wanting this.
2. The slider is already cramped for space!

I'll jump on this if there's more demand.

**Comment by MohamedBassem** [comment]
Came here to ask for the same feature :) Very useful when looking at logs from different timezones for example.

**Comment by m1keil** [comment]
+1 for this.

Hopefully one day.
