### ISSUE TITLE
Crashes on click

### ISSUE THREAD

**Issue by prokher** [abhishekbanthia/Clocker#7]
I launch Clocker, click on its icon in the menubar and it crashes:

> Clocker.app/Contents/MacOS/Clocker
> 2016-09-01 16:08:46.626 Clocker[2699:29923] [Crashlytics] Version 3.4.1 (92)
> 2016-09-01 16:08:46.627 Clocker[2699:29923] [Crashlytics] Running on MacBookPro12,1, 10.11.6 (15G31)
> 2016-09-01 16:08:46.627 Clocker[2699:29923] [Crashlytics:Crash:Client] Background session uploading supported
> 2016-09-01 16:08:46.636 Clocker[2699:29923] [Fabric] Initialized with kit versions: {
>     "com.twitter.answers.mac" = "1.0.1";
>     "com.twitter.crashlytics.mac" = "3.4.1";
>     "io.fabric.sdk.mac" = "1.6.1";
> }
> 2016-09-01 16:08:46.636 Clocker[2699:29936] [Crashlytics:Answers] Answers enabled with settings: {
>     "flush_interval_secs" = 300;
>     "flush_on_background" = 1;
>     "max_byte_size_per_file" = 8000;
>     "max_file_count_per_send" = 1;
>     "max_pending_send_file_count" = 100;
>     "sampling_rate" = 1;
>     "track_custom_events" = 1;
>     "track_predefined_events" = 1;
>     "track_view_controllers" = 0;
>     url = "https://e.crashlytics.com/spi/v2/events";
> }
> 2016-09-01 16:08:46.636 Clocker[2699:29936] [Crashlytics:Answers] Logging events to session directory /Users/prokher/Library/Containers/com.abhishek.Clocker/Data/Library/Caches/com.crashlytics.data/com.abhishek.Clocker/analytics/v1/ACTIVE/1472735326631_3bf05a8b8988409cab37aeccdbeef8e4
> 2016-09-01 16:08:46.646 Clocker[2699:29923] [Crashlytics:Answers] Logging previous session crashed event {date: 2016-09-01 13:05:24 +0000}
> 2016-09-01 16:08:46.674 Clocker[2699:29964] [Crashlytics:Crash:Reports] Packaged id 4d6bf79af1d74d308839ccb2e90e36f2 for submission
> 2016-09-01 16:08:46.674 Clocker[2699:29964] [Crashlytics:Crash:Reports] Submitting report
> 2016-09-01 16:08:46.674 Clocker[2699:29964] [Crashlytics:Crash:Reports] Submitting async /Users/prokher/Library/Containers/com.abhishek.Clocker/Data/Library/Caches/com.crashlytics.data/com.abhishek.Clocker/v3/prepared/20E0899D-6F56-4624-ACC8-191BDB8041DA.multipartmime
> 2016-09-01 16:08:47.728 Clocker[2699:29964] [Fabric] settings downloaded successfully
> 2016-09-01 16:08:47.729 Clocker[2699:29964] [Fabric] Settings are available for consumption
> 2016-09-01 16:08:47.729 Clocker[2699:29936] [Crashlytics:Answers] Answers enabled with settings: {
>     "flush_interval_secs" = 300;
>     "flush_on_background" = 1;
>     "max_byte_size_per_file" = 8000;
>     "max_file_count_per_send" = 1;
>     "max_pending_send_file_count" = 100;
>     "sampling_rate" = 1;
>     "track_custom_events" = 1;
>     "track_predefined_events" = 1;
>     "track_view_controllers" = 0;
>     url = "https://e.crashlytics.com/spi/v2/events";
> }
> 2016-09-01 16:08:48.635 Clocker[2699:29937] [Crashlytics:Crash:Reports] completed submission of /Users/prokher/Library/Containers/com.abhishek.Clocker/Data/Library/Caches/com.crashlytics.data/com.abhishek.Clocker/v3/prepared/20E0899D-6F56-4624-ACC8-191BDB8041DA.multipartmime
> 2016-09-01 16:08:48.636 Clocker[2699:29937] [Crashlytics:Crash] report submission successful
> 2016-09-01 16:08:53.113 Clocker[2699:29923] **\* -[NSCalendar component:fromDate:]: date cannot be nil
> 2016-09-01 16:08:53.118 Clocker[2699:29923](0   CoreFoundation                      0x00007fff90ef64f2 __exceptionPreprocess + 178
>         1   libobjc.A.dylib                     0x00007fff95f83f7e objc_exception_throw + 48
>         2   CoreFoundation                      0x00007fff90eccbac -[NSCalendar component:fromDate:] + 316
>         3   Clocker                             0x0000000100a16145 Clocker + 196933
>         4   Clocker                             0x0000000100a16aab Clocker + 199339
>         5   Clocker                             0x0000000100a0bb5b Clocker + 154459
>         6   AppKit                              0x00007fff9204821c -[NSTableView%28NSTableViewViewBased%29 makeViewForTableColumn:row:] + 76
>         7   AppKit                              0x00007fff92047c35 -[NSTableRowData _addViewToRowView:atColumn:row:] + 283
>         8   AppKit                              0x00007fff9204798e -[NSTableRowData _addViewsToRowView:atRow:] + 184
>         9   AppKit                              0x00007fff920461a7 -[NSTableRowData _initializeRowView:atRow:] + 390
>         10  AppKit                              0x00007fff92044907 -[NSTableRowData _addRowViewForVisibleRow:withPriorView:] + 416
>         11  AppKit                              0x00007fff9204469b -[NSTableRowData _addRowViewForVisibleRow:withPriorRowIndex:inDictionary:withRowAnimation:] + 299
>         12  AppKit                              0x00007fff92043461 -[NSTableRowData _unsafeUpdateVisibleRowEntries] + 1697
>         13  AppKit                              0x00007fff92042d22 -[NSTableRowData updateVisibleRowViews] + 233
>         14  AppKit                              0x00007fff9204269b -[NSTableView layout] + 178
>         15  AppKit                              0x00007fff91fe13e7 -[NSView _doLayout] + 53
>         16  AppKit                              0x00007fff91fe109f -[NSView _layoutSubtreeWithOldSize:] + 324
>         17  AppKit                              0x00007fff91fe12fb -[NSView _layoutSubtreeWithOldSize:] + 928
>         18  AppKit                              0x00007fff91fe12fb -[NSView _layoutSubtreeWithOldSize:] + 928
>         19  AppKit                              0x00007fff91fe12fb -[NSView _layoutSubtreeWithOldSize:] + 928
>         20  AppKit                              0x00007fff91f534fb -[NSView setFrameSize:] + 1727
>         21  AppKit                              0x00007fff91f6b90d -[NSView setFrame:] + 476
>         22  AppKit                              0x00007fff91f77f15 -[NSView resizeWithOldSuperviewSize:] + 409
>         23  AppKit                              0x00007fff91f778a9 -[NSView resizeSubviewsWithOldSize:] + 318
>         24  AppKit                              0x00007fff91f53517 -[NSView setFrameSize:] + 1755
>         25  AppKit                              0x00007fff920e3c47 -[NSNextStepFrame setFrameSize:] + 201
>         26  AppKit                              0x00007fff91f6b90d -[NSView setFrame:] + 476
>         27  Foundation                          0x00007fff9864e4d4 ___NSSetRectValueAndNotify_block_invoke + 73
>         28  Foundation                          0x00007fff984dd8b5 -[NSObject%28NSKeyValueObservingPrivate%29 _changeValueForKey:key:key:usingBlock:] + 1049
>         29  Foundation                          0x00007fff985b63a5 _NSSetRectValueAndNotify + 335
>         30  AppKit                              0x00007fff91f7821d -[NSView resizeWithOldSuperviewSize:] + 1185
>         31  AppKit                              0x00007fff91fe05a8 -[NSView layoutSubtreeIfNeeded] + 902
>         32  AppKit                              0x00007fff91ffff21 -[NSWindow%28NSConstraintBasedLayout%29 _layoutViewTree] + 82
>         33  AppKit                              0x00007fff91fe68e9 -[NSWindow _setFrame:updateBorderViewSize:] + 1059
>         34  AppKit                              0x00007fff91fff379 -[NSWindow _oldPlaceWindow:] + 1075
>         35  AppKit                              0x00007fff91ffe74e -[NSWindow _setFrameCommon:display:stashSize:] + 2743
>         36  AppKit                              0x00007fff91ffdc88 -[NSWindow _setFrame:display:allowImplicitAnimation:stashSize:] + 222
>         37  AppKit                              0x00007fff91ffdba3 -[NSWindow setFrame:display:] + 67
>         38  AppKit                              0x00007fff920e3529 -[NSWindow%28NSConstraintBasedLayout%29 _fromConstraintsSetWindowFrame:] + 205
>         39  AppKit                              0x00007fff92072799 -[NSWindow%28NSConstraintBasedLayout%29 _changeWindowFrameFromConstraintsIfNecessary] + 633
>         40  Foundation                          0x00007fff985380c2 -[NSISEngine withBehaviors:performModifications:] + 155
>         41  AppKit                              0x00007fff920724e2 -[NSWindow%28NSConstraintBasedLayout%29 layoutIfNeeded] + 215
>         42  AppKit                              0x00007fff920723f4 -[NSWindow _setUpFirstResponderBeforeBecomingVisible] + 63
>         43  AppKit                              0x00007fff920717d0 -[NSWindow _doWindowWillBeVisibleAsSheet:] + 169
>         44  AppKit                              0x00007fff920705d2 -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 1377
>         45  AppKit                              0x00007fff9206ef5f -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 894
>         46  AppKit                              0x00007fff9206eb83 -[NSWindow orderWindow:relativeTo:] + 159
>         47  AppKit                              0x00007fff9212dfc6 -[NSWindow makeKeyAndOrderFront:] + 106
>         48  Clocker                             0x0000000100a0b123 Clocker + 151843
>         49  Foundation                          0x00007fff984dd8b5 -[NSObject%28NSKeyValueObservingPrivate%29 _changeValueForKey:key:key:usingBlock:] + 1049
>         50  Foundation                          0x00007fff98548ab7 _NSSetCharValueAndNotify + 268
>         51  Clocker                             0x0000000100a126f9 Clocker + 182009
>         52  libsystem_trace.dylib               0x00007fff8805007a _os_activity_initiate + 75
>         53  AppKit                              0x00007fff92195dbd -[NSApplication sendAction:to:from:] + 460
>         54  Clocker                             0x0000000100a034c8 Clocker + 120008
>         55  AppKit                              0x00007fff926f93c9 -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
>         56  AppKit                              0x00007fff926fa3ad -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
>         57  AppKit                              0x00007fff92139539 -[NSWindow sendEvent:] + 517
>         58  AppKit                              0x00007fff92607849 -[NSStatusBarWindow sendEvent:] + 281
>         59  AppKit                              0x00007fff920b9a38 -[NSApplication sendEvent:] + 2540
>         60  AppKit                              0x00007fff91f20df2 -[NSApplication run] + 796
>         61  AppKit                              0x00007fff91eea368 NSApplicationMain + 1176
>         62  libdyld.dylib                       0x00007fff9bec35ad start + 1)
> Illegal instruction: 4
> ✘-ILL

**Comment by abhishekbanthia** [comment]
Thank you for the logs.

Can you tell me your local date format, time, calendar that's been set in System Preferences? I have attached a reference screenshot of my preferences. 

<img width="780" alt="screen shot 2016-09-01 at 2 36 08 pm" src="https://cloud.githubusercontent.com/assets/8280282/18185273/a91dc0ec-7051-11e6-941e-76a06a59eabf.png">

**Comment by prokher** [comment]
Here it is:

[image: Inline image 1]

**Comment by abhishekbanthia** [comment]
Can you attach the image again?

**Comment by prokher** [comment]
Why? Anyway, OK, here it is:

[image: Inline image 1]

**Comment by abhishekbanthia** [comment]
Hi Prokher, I'm unable to see the image. Here's what I'm seeing:

<img width="846" alt="screen shot 2016-09-06 at 1 40 46 pm" src="https://cloud.githubusercontent.com/assets/8280282/18290247/a496f7fc-7437-11e6-9258-337d58675d96.png">

**Comment by prokher** [comment]
OK, seem's github can not process images attached to email. Let's do this through github iface :)

![unnamed](https://cloud.githubusercontent.com/assets/399393/18290344/358db398-7494-11e6-943c-916f6baeed67.png)

**Comment by abhishekbanthia** [comment]
Thank you for the image. Can you let me know if Clocker works for you if you revert to default time and date settings?

**Comment by prokher** [comment]
Yes, it does.

**Comment by prokher** [comment]
​BTW, switching back to my setting does not make it crash. So we at least
found a workaround.​

**Comment by prokher** [comment]
Further experiments exposed another problem: it shows the wrong day (Monday
instead of Wednesday) when calendar is “ISO 8601”, if I switch it to
Gregorian it shows proper day. I use ISO 8601 because it has different week
numbering from Gregorian one.

**Comment by abhishekbanthia** [comment]
Interesting. Thanks for the information. Investigating.

**Comment by prokher** [comment]
More to this. I’ve found what makes this crash. When I use custom time/date
format it starts crashing again.

**Comment by abhishekbanthia** [comment]
Here's a build that works around the problem you're facing:

[Clocker.app.zip](https://github.com/abhishekbanthia/Clocker/files/573602/Clocker.app.zip)

**Comment by prokher** [comment]
Thank you, seems it eventually works well.
